#!/usr/bin/env python
"""Native-git fallback for DRISHTA's TEXT-ONLY workflow gates.

WHY THIS EXISTS (2026-10-07). `pre_tool_checks.py` is registered as a Claude
Code `PreToolUse` hook in `.claude/settings.json`. That registration is INERT:
Accenture's managed settings set `allowManagedHooksOnly: true`, which per
Anthropic's docs means "hooks in your user, project, and local settings files
don't run and aren't listed." Verified live -- a Bash command containing
`streamlit run` executed instead of being blocked. The script is healthy; only
the Claude-Code-side INVOCATION is blocked. Here git is the caller, so no
managed-settings policy can switch it off.

================== WHAT THIS DOES AND DOES NOT COVER ==================
ENFORCES, on an ordinary `git commit` only:
  * Hard Rule #4 -- an Opus review citation when a `_GATE_FILES` member is staged
  * Hard Rule #5 -- `Design =` / `Build =` trailers on a `feat(` commit

DOES NOT RUN pytest. DOES NOT RUN the antipattern check. Run both by hand:
    python -m pytest
    python scripts/check_antipatterns.py

DOES NOT GATE these, by design (see "amend" below and the 2026-10-07 reviews) --
none of them runs `commit-msg` at all, except amend which is indistinguishable:
    git commit --amend   cherry-pick   revert --no-edit   rebase pick/squash/fixup   git am
A BLOCKED message from this hook therefore means "the two text gates ran and
one failed." It never means the full pre-commit pipeline is live.

It reads the WORKING-TREE copies of this file and of `pre_tool_checks.py`, not
the staged ones -- so an unstaged local edit weakening `_GATE_FILES` weakens the
gate for the commit in progress. The PreToolUse hook has the same exposure.
=======================================================================

WHY NO AMEND DETECTION. Two Opus review rounds (2026-10-07) both found amend
handling broken, the second time reproducing it. The prepare-commit-msg
approach cannot work: git passes `source=message` for BOTH `--amend -m` and
`--amend -F`, which is this project's own convention, so an amend is
indistinguishable from a normal commit at that layer. Only `--amend --no-edit`
and editor amends pass `commit`. A correct implementation needs a
`reference-transaction` hook, which was judged not worth the complexity for a
stopgap. **So: an amend that drops a review citation will NOT be caught here.**
Treat `git commit --amend` on a gate-file commit as a manual-verification case.

WHY IMPORT, NOT SUBPROCESS. v1 of this file shelled out to `pre_tool_checks.py`,
which spawned pytest, whose `tmp_git_repo` fixture then ran `git init/add/commit`
against the REAL repository -- because git exports `GIT_INDEX_FILE` (absolute,
for `-a` and pathspec commits) and `GIT_DIR` (worktrees) into the hook
environment. Review reproduced an index pointing at non-existent blobs,
`.git/config` rewritten to `user.email=test@example.com`, and ~57-deep hook
recursion. **Never spawn pytest from a git hook without scrubbing
`git rev-parse --local-env-vars` from the child environment.** Importing the
predicates avoids that class entirely; the only subprocesses here are git
queries, which SHOULD inherit GIT_INDEX_FILE since at commit-msg time it
correctly names the real commit index.

NO LOGIC IS DUPLICATED -- the regexes, `_GATE_FILES` and the predicates are
imported from `pre_tool_checks.py`, so the two entry points cannot drift.

FAILS CLOSED. Every error path blocks: an unreadable message, a failing git
query, a stripspace failure, an unknown mode, any exception. `--no-verify` is
the single deliberate escape hatch. Failing open is the exact silent-gate bug
this file exists to fix, so there is no "benefit of the doubt" path.

INSTALL / RE-INSTALL:  python .claude/hooks/git_hook_adapter.py --install
`.git/hooks/` is outside the work tree, so this is per-clone and must be re-run
after a fresh clone, and in any linked worktree that predates this file.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))

_SHIM = """#!/bin/sh
# DRISHTA text-only workflow gates -- native-git fallback.
# Generated by .claude/hooks/git_hook_adapter.py; see that file for scope.
# Bypass with --no-verify, same as any git hook.
exec python .claude/hooks/git_hook_adapter.py commit "$@"
"""

# `git commit -v` appends the staged diff below a scissors line. That diff can
# contain text satisfying these very gates -- docs/cost-routing.md and several
# docs/plans/*.md hold REAL citation lines, and the docs-sync rule makes
# doc+gate-file commits routine. `git stripspace --strip-comments` removes only
# the marker line itself, not the diff beneath it, so the message must be cut
# here first. Reproduced in review: an editor-driven `git commit -v` with
# constants.py staged passed with no citation of its own.
_SCISSORS_RE = re.compile(r"^\S+ -+ >8 -+\s*$", re.MULTILINE)


def _git(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], capture_output=True, text=True,
        encoding="utf-8", errors="replace", timeout=30,
    )


def _git_lines(*args: str) -> list[str]:
    """Run a git query, or RAISE. A silently-empty result disables the gate."""
    r = _git(*args)
    if r.returncode != 0:
        raise RuntimeError(f"`git {' '.join(args)}` failed: {r.stderr.strip()}")
    return [ln.strip() for ln in r.stdout.splitlines() if ln.strip()]


def _install() -> int:
    r = _git("rev-parse", "--git-path", "hooks")
    hooks_dir = r.stdout.strip() if r.returncode == 0 else os.path.join(".git", "hooks")
    hooks_dir = os.path.abspath(hooks_dir)
    if f"{os.sep}.git{os.sep}" not in hooks_dir + os.sep:
        print(
            f"WARNING: core.hooksPath resolves outside .git ({hooks_dir}); "
            "installing there may overwrite hooks you did not create.",
            file=sys.stderr,
        )
    os.makedirs(hooks_dir, exist_ok=True)
    path = os.path.join(hooks_dir, "commit-msg")
    if os.path.isfile(path):
        with open(path, encoding="utf-8", errors="replace") as fh:
            if "git_hook_adapter" not in fh.read():
                print(f"WARNING: overwriting an existing unrelated hook at {path}",
                      file=sys.stderr)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(_SHIM)
    os.chmod(path, 0o755)
    print(f"installed {path}\n")
    print("TEXT GATES ONLY -- review citation + provenance trailers, on an")
    print("ordinary `git commit`. pytest and the antipattern check are NOT run,")
    print("and --amend / cherry-pick / revert / rebase are NOT gated.")
    return 0


def _clean_message(raw: str) -> str:
    """Cut the `-v` diff, then strip `#` comments. Over-cutting fails CLOSED."""
    m = _SCISSORS_RE.search(raw)
    if m:
        raw = raw[: m.start()]
    r = subprocess.run(
        ["git", "stripspace", "--strip-comments"], input=raw,
        capture_output=True, text=True, encoding="utf-8", errors="replace",
        timeout=30,
    )
    if r.returncode != 0:
        raise RuntimeError(f"`git stripspace` failed: {r.stderr.strip()}")
    return r.stdout


def _changed_files() -> list[str]:
    """Files this commit will contain.

    At commit-msg time the index is FINAL -- git has already applied `-a` and
    any pathspec -- so `diff --cached` alone is complete here, unlike the
    PreToolUse path which must infer them from the command string.

    `--no-renames` because rename detection reports only the NEW path: a
    `git mv stock_analyzer/constants.py constants_old.py` would otherwise drop
    the gate-file name and skip the citation gate (reproduced in review).
    """
    return sorted(set(_git_lines("diff", "--cached", "--name-only", "--no-renames")))


def _run_gates(argv: list[str]) -> int:
    # Shim is `... git_hook_adapter.py commit "$@"`, and git passes commit-msg
    # exactly one argument. So argv == [script, "commit", <message file>].
    # (v2 got this mapping wrong for a second hook and the bug survived a
    # hand-written unit test that skipped the shim entirely. Test THROUGH it.)
    msg_file = argv[2] if len(argv) > 2 else ""
    if not msg_file or not os.path.isfile(msg_file):
        print(
            f"BLOCKED (workflow gates): commit message file not readable "
            f"({msg_file!r}); cannot verify the required trailers.",
            file=sys.stderr,
        )
        return 1

    sys.path.insert(0, _HERE)
    import pre_tool_checks as ptc  # noqa: E402 - path set above

    with open(msg_file, encoding="utf-8", errors="replace") as fh:
        message = _clean_message(fh.read())

    changed = _changed_files()
    failures: list[str] = []

    gated = ptc._gate_files_staged(changed)
    if gated and not ptc._has_review_citation(message):
        failures.append(
            "Hard Rule #4 -- decision-engine / DB-write file(s) staged with no "
            "Opus review citation:\n    " + "\n    ".join(gated) + "\n"
            "  Add to the commit body:\n"
            "    Review = Opus reviewer (<resolved model>): SHIP|FIX-FIRST, "
            "N blocking; <notes>"
        )

    if ptc._is_feature_commit(message):
        missing = ptc._missing_provenance_trailers(message)
        if missing:
            failures.append(
                "Hard Rule #5 -- feature commit missing "
                + " and ".join(missing) + " trailer(s).\n"
                "  Design = planner (<model>): <verdict>  OR  Design = lead -- <why>\n"
                "  Build  = implementer (<model>)         OR  Build  = lead -- <why>"
            )

    if failures:
        print(
            "\n\n".join("BLOCKED (workflow gates): " + f for f in failures),
            file=sys.stderr,
        )
        print(
            "\n[native git hook] TEXT GATES ONLY. pytest and the antipattern "
            "check did NOT run -- run them by hand. Bypass with --no-verify.",
            file=sys.stderr,
        )
        return 1

    # Say so on success too, and name which checks were APPLICABLE rather than
    # just "passed" -- a bare pass line reads as "a citation was verified" even
    # on a commit where no gate file was staged (including the amend gap, where
    # nothing was checked at all). Silence, or vagueness, is the inverse of the
    # stale "trust the hook" advice this whole effort exists to correct.
    cite = (
        f"citation: checked ({len(gated)} gate file(s))" if gated
        else "citation: N/A (no gate files staged)"
    )
    trailers = (
        "trailers: checked" if ptc._is_feature_commit(message)
        else "trailers: N/A (not a feat( commit)"
    )
    print(
        f"[native git hook] Text gates passed -- {cite}; {trailers}. "
        "pytest + antipattern check did NOT run; --amend / cherry-pick / "
        "revert / rebase / am are NOT gated.",
        file=sys.stderr,
    )
    return 0


def main() -> None:
    if "--install" in sys.argv:
        sys.exit(_install())

    if len(sys.argv) > 1 and sys.argv[1] == "commit":
        try:
            sys.exit(_run_gates(sys.argv))
        except Exception as exc:  # noqa: BLE001 - FAIL CLOSED, see docstring
            print(
                f"BLOCKED (workflow gates): the gate adapter itself failed "
                f"({type(exc).__name__}: {exc}).\n"
                "This is NOT a pass. Fix the adapter, or use --no-verify if certain.",
                file=sys.stderr,
            )
            sys.exit(1)

    print(
        f"BLOCKED (workflow gates): unknown adapter invocation {sys.argv[1:]!r}.",
        file=sys.stderr,
    )
    sys.exit(1)


if __name__ == "__main__":
    main()
